services:
  # Servicio Web
  - type: web
    name: ecofact-project
    runtime: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "gunicorn EcoFactProject.wsgi:application -c gunicorn.conf.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: USE_POSTGRESQL
        value: True
      - key: DATABASE_URL
        fromDatabase:
          name: ecofact-db
          property: connectionString
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: True
      - key: DEFAULT_FROM_EMAIL
        sync: false

  # Base de datos PostgreSQL
  - type: pserv
    name: ecofact-db
    runtime: postgresql
    plan: free
    databaseName: ecofact
    user: ecofact
